name: Validate and publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-build-test-publish-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        # Use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`).
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Run tests
        run: yarn run test

      - name: Azure Login
        uses: azure/login@v1
        with:
          # https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux
          # AZURE_CREDENTIALS retrieved with az ad sp create-for-rbac --name "Azure Functions TypeScript" --role contributor --sdk-auth.
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create or update Azure resources
        run: ./.github/workflows/create-azure-resources.sh ${GITHUB_HEAD_REF}

      - name: Install production Node modules
        run: (cd dist; yarn install --frozen-lockfile --production)

      - name: Publish code to Azure
        run: ./.github/workflows/publish-to-azure.sh ${GITHUB_HEAD_REF}

      - name: Run end-to-end tests
        run: yarn run test-e2e-save-results
